# Generated by Django 4.1.3 on 2023-04-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_blog_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(max_length=255),
        ),
    ]
