# Generated by Django 4.1.3 on 2023-04-28 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_blog_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality', models.CharField(choices=[('mental health', 'Mental Health'), ('heart disease', 'Heart Disease'), ('covid19', 'COVID-19'), ('immunization', 'Immunization')], max_length=30, verbose_name='Required Speciality')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Appointment Time')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_id_ref', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_id_ref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
